### ISSUE TITLE
Keyword lists:  Add textbox that will filter values in multi-select

### ISSUE THREAD

**Issue by jzichichi** [USEPA/EPA_Environmental_Dataset_Gateway#79]
Enhancement requested by Ana - with Keywords sections (EPA, ISO, and Place), add a  textbox where user may enter text to filter values in the keyword multi-select list.

**Comment by aergul** [comment]
This is now implemented

**Comment by jzichichi** [comment]
@aergul - love it.  2 things.  

1. As soon as I make a selection, the filtering is *undone* and the whole list shows again, which feels sort of weird to me.  I would think it would stay filtered until the user removed the text they'd typed in the text box?  @torrin47, maybe you feel differently about that than I do though. 
2.  The location of the text box where I enter text to do my filtering feels too far to the right.  Possible to move it left or is that impossible due to the alignment with the section tool?

![Untitled.png](https://images.zenhubusercontent.com/5b889669f9c188212a6dc1cd/5083f6d9-735b-4090-850d-b73910093934)

**Comment by aergul** [comment]
1. The reason that the filter is cleared after a selection is to avoid user having to do it. For example, if you are selecting New England states in your place keywords, there isn't really much commonality to reuse from one selection to the next. I could be convinced otherwise as there is a narrow use case of "I happen to know several keywords I want to select have an 'e' in them and I want to select in one go".

2- This is addressed now

**Comment by torrin47** [comment]
:thumbsup:

**Comment by jzichichi** [comment]
OK, I can see the value of it clearing after selection.  I will move this over; the placement of the text box for filtering looks good.

**Comment by torrin47** [comment]
This issue was moved to USEPA/EPA_Non-geo_Metadata_Editor#8
